- name: Place Elasticsearch index creation files
  copy:
    src: "files/{{ item }}"
    dest: "/tmp/{{ item }}"
  with_items:
    - features.json
    - records.json
    - searchlogs.json

- name: Create Elasticsearch indexes
  uri:
    url: "{{ geonetwork['es']['url'] }}/{{ item }}"
    method: PUT
    body: "{{ lookup('file','/tmp/' + item + '.json') }}"
    body_format: json
  ignore_errors: true
  with_items:
    - features
    - records
    - searchlogs

- name: Stop tomcat service to avoid autodeploy
  systemd:
    name: tomcat
    state: stopped

- name: Create home folder for geonetwork related data, config, etc
  file:
    path: "{{ geonetwork['home'] }}"
    state: directory
    owner: tomcat
    group: tomcat
    mode: 'g+rw'

- name: Create data dir for geonetwork
  file:
    path: "{{ geonetwork['home'] }}/data"
    state: directory
    owner: tomcat
    group: tomcat
    mode: 'g+rw'

- name: Create folder for geonetwork app
  file:
    path: "{{ geonetwork['tomcat_dir'] }}"
    state: directory

- name: Check if geonetwork has been deployed already.
  find:
    paths: "{{ tomcat['home'] }}/webapps/geonetwork"
    file_type: directory
    patterns: "*"
  register: geonetwork_dir_files

- name: Obtain and decompress geonetwork
  unarchive:
    src: "{{ geonetwork['package_location'] }}"
    dest: "{{ geonetwork['tomcat_dir'] }}"
    remote_src: "{{ geonetwork['remote'] }}"
  when: geonetwork["redeploy"] or geonetwork_dir_files.matched|int == 0

- name: Copy srv.xml
  template:
    src: srv.xml.j2
    dest: "{{ geonetwork['tomcat_dir'] }}/WEB-INF/config-node/srv.xml"

- name: Copy jdbc.properties
  template:
    src: jdbc.properties.j2
    dest: "{{ geonetwork['tomcat_dir'] }}/WEB-INF/config-db/jdbc.properties"

- name: Copy config.properties
  template:
    src: config.properties.j2
    dest: "{{ geonetwork['tomcat_dir'] }}/WEB-INF/config.properties"

- name: Copy log4j.xml
  template:
    src: log4j.xml.j2
    dest: "{{ geonetwork['tomcat_dir'] }}/WEB-INF/classes/log4j.xml"

- name: Set tomcat user as owner of geonetwork related files in tomcat dir
  file:
    path: "{{ geonetwork['tomcat_dir'] }}"
    owner: tomcat
    group: tomcat
    recurse: yes
    mode: 'g+rw'

- name: Restart tomcat service
  systemd:
    name: tomcat
    state: started
  become: true
