deployment_type: "{{ i_deployment_type | default('local') }}"

# If deployment_type == aws
db_endpoint: "{{ i_db_endpoint | default('') }}"

tomcat_pkg_url: "{{ i_tomcat_pkg_url | default('http://apache.uniminuto.edu/tomcat/tomcat-7/v7.0.78/bin/apache-tomcat-7.0.78.tar.gz') }}"
geonetwork_pkg_url: "{{ i_geonetwork_pkg_url | default('http://downloads.sourceforge.net/project/geonetwork/GeoNetwork_opensource/v3.2.1/geonetwork.war') }}"
