---
- hosts: tag_Name_elasticsearchserver
  pre_tasks:
    - name: Install Java
      yum: name="java-1.8.0-openjdk.x86_64" state=present
      become: true
  roles:
    - elasticsearch
  become: true
